steps:
  - title: Klasse
    description: In diesem Schritt wird die Klasse ausgewählt
    fields:
      - type: select
        data:
          - Zauberer
          - Krieger
      - type: number
      - type: text
  - title: Spezies
    description: In diesem Schritt wird die Spezies ausgewählt
    fields:
      - type: select
        data:
          - Mensch
          - Elf
          - Halbelf
          - Zwerg
