/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON Schema für die DSA Helden Erstellung
 */
export interface JSONSchemaFurDieDSAHeldenErstellung {
  /**
   * Die einzelnen Schritte der Erstellung
   */
  steps: {
    title: string;
    description: string;
    fields?: {
      id: string;
      type: 'text' | 'number' | 'select';
      data: string[];
    }[];
  }[];
}
