/* eslint-disable no-use-before-define */
/**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */

export type FieldJson = (({
  [k: string]: unknown;
} | {
  [k: string]: unknown;
}) & {
  id: string;
  label: string;
  type: ('text' | 'number' | 'select');
  data?: string[];
})

/**
 * JSON Schema für die DSA Helden Erstellung
 */
export interface JSONSchemaFurDieDSAHeldenErstellung {
/**
 * Die einzelnen Schritte der Erstellung
 */
  steps: StepJson[];
}
export interface StepJson {
  id: string;
  title: string;
  description: string;
  sections?: SectionJson[];
}
export interface SectionJson {
  title?: string;
  description?: string;
  fields?: FieldJson[];
}
