import { compileFromFile } from 'json-schema-to-typescript';
import { writeFileSync } from 'fs';
import { execSync } from 'child_process';

void compileFromFile('./schema/schema.json', {
  cwd: './schema',
  declareExternallyReferenced: true,
  enableConstEnums: true,
  unreachableDefinitions: false,
  strictIndexSignatures: false,
  bannerComment: `/* eslint-disable no-use-before-define */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */`,

  format: false,
}).then((ts) => {
  writeFileSync('src/modules/creator/schema-generated.types.d.ts', ts);

  execSync('npx eslint ./src/modules/creator/schema-generated.types.d.ts --fix');
});
