import { compileFromFile } from 'json-schema-to-typescript';
import { ESLint } from 'eslint';

void compileFromFile('./schema/schema.json', {
  cwd: './schema',
  declareExternallyReferenced: true,
  enableConstEnums: true,
  unreachableDefinitions: false,
  strictIndexSignatures: false,
  bannerComment: `/* eslint-disable no-use-before-define */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */`,

  format: false,
}).then(async (ts) => {
  const eslint = new ESLint({ fix: true });

  const result = await eslint.lintText(ts, {
    filePath: './src/modules/creator/schema.types.d.ts',
  });

  void ESLint.outputFixes(result);
});
